# A list of factions and their members
factions:
  factionOne:
    name: "Faction #1"
    leader: "Sean"
    members: ["Sean", "Nathan", "Jerry", "Jenna", "Dan Pham", "Hoon", "Xobo"]
  factionTwo:
    name: "Faction #2"
    leader: "Bryce"
    members: ["Bryce", "Ethan", "Allen", "Revanth", "Kenny"]
  factionThree:
    name: "Faction #3"
    leader: "Jazz"
    members: ["Jazz", "Matthew", "Gabe", "Ash", "Arman", "Ben"]
  factionFour:
    name: "Faction #4"
    leader: "John"
    members: ["John", "ASU", "Josh", "Amy", "Samj", "Apollo"]
  factionFive:
    name: "Faction #5"
    leader: "Vihaan"
    members: ["Vihaan", "Anwar", "Best Friend", "Eric", "Aaron", "Carolyn"]

# Reward settings
enderDragonReward:
  block: YELLOW_SHULKER_BOX
  reward: ELYTRA
  particle: CRIT_MAGIC
  hologramText: "§6§lClick to claim your reward!"
  killMessage: "§6§lThe Ender Dragon has been killed! Claim the reward by clicking the block on top of the ender egg!"
  rewardMessage: "§6§lThe reward has been claimed by"
  rewardMessageToPlayer01: "§6§lYou have been given an"
  rewardMessageToPlayer02: "§6§las a reward"